project:
  type: website
  output-dir: docs

website:
  title: "Quarto Template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - editing.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true
    toc: true

editor: visual

