project:
  type: website
  output-dir: docs

website:
  title: "Quarto Template"
  reader-mode: false
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/p-lemercier/Quarto-website-template
          - text: Report a Bug
            url: https://github.com/p-lemercier/Quarto-website-template/issues
    left:
      - text: Home
        href: index.qmd
      - text: "Other languages"
        menu:
          - observable_js.qmd
          - sas.qmd
          - stata.qmd
      - editing.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    df-print: paged
    code-fold: true
    code-copy: true
    code-link: true
    code-tools:
      source: false 
      toggle: true
    code-block-bg: true
    fig-cap-location: top
    toc: true
    css: styles.css

editor: visual
lang: en
