project:
  type: website
  output-dir: docs

website:
  title: "Quarto Template"
  reader-mode: true
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - href: index.qmd
        text: Home
      - editing.qmd
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    code-fold: true
    toc: true

editor: visual

